### ISSUE TITLE
ics:deploy skipDownload:false does not download files

### ISSUE THREAD

**Issue by mehrad-rafigh** [isomorphic-software/isc-maven-plugin#4]
Hi there,

I am currently trying to use this plugin to download the Power Edition of SmartGWT 5.0. It appears that the plugin logins in with the provided credentials and it creates the path to download the files, but it does not download anything. It just creates an empty directory.

**Comment by bbruyn** [comment]
Whatever's happening, the reason behind it is probably included in your console output.  You might have better luck asking for help on the SmartGWT forum.  Be sure to include the command you issued and its result.
